# Generated by Django 4.2.26 on 2025-11-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity_pct', models.FloatField()),
                ('tilt', models.BooleanField()),
                ('vibration', models.BooleanField()),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime', to='core.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity_pct', models.FloatField()),
                ('tilt', models.BooleanField()),
                ('vibration', models.BooleanField()),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='core_sensor_recorde_78bad6_idx'), models.Index(fields=['sensor', 'recorded_at'], name='core_sensor_sensor__8938df_idx')],
            },
        ),
    ]
