# Generated by Django 5.2.3 on 2025-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pulse', models.PositiveIntegerField(help_text='Nivel capturado por el sensor de vibración')),
                ('hit', models.BooleanField(default=False, help_text='Golpe detectado por el sensor de vibración')),
                ('inclination', models.BooleanField(default=False, help_text='Inclinación detectada')),
                ('humidity_percent', models.FloatField(help_text='Humedad relativa calibrada (0-100%)')),
                ('humidity_raw', models.PositiveIntegerField(help_text='Dato crudo del sensor de 0 a 1024')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_6f0ca4_idx')],
            },
        ),
    ]
