# Generated by Django 5.2.3 on 2025-11-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alerta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.PositiveIntegerField()),
                ('soil_raw', models.PositiveIntegerField(help_text='Humedad cruda (0-1024)')),
                ('soil_pct', models.FloatField(help_text='Humedad porcentual')),
                ('tilt', models.BooleanField(default=False, help_text='Inclinacion detectada')),
                ('vib_pulse', models.PositiveIntegerField(help_text='Pulso reportado por el sensor de vibracion')),
                ('vib_hit', models.BooleanField(default=False, help_text='Golpe detectado por el sensor de vibracion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='monitoring.sensorpacket')),
            ],
            options={
                'ordering': ['-packet__timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
        migrations.AddIndex(
            model_name='sensorsample',
            index=models.Index(fields=['packet', 'sample_id'], name='monitoring__packet__6466b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorsample',
            unique_together={('packet', 'sample_id')},
        ),
    ]
