# Generated by Django 5.2.3 on 2025-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_sensorpacket_sensorsample_delete_sensorreading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorpacket',
            name='seq',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
